[internal]

exten => 1001,1,MixMonitor(1001-${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)}.wav)
 same => n,Dial(PJSIP/1001,20)
 same => n,Hangup()

exten => 1002,1,MixMonitor(1002-${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)}.wav)
 same => n,Dial(PJSIP/1002,20)
 same => n,Hangup()
